"""status_col

Revision ID: 6c55eac6ffca
Revises: f4a3dc6d565c
Create Date: 2022-09-28 23:59:18.496045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c55eac6ffca'
down_revision = 'f4a3dc6d565c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'status')
    # ### end Alembic commands ###
