version: '3.9'

x-common-variables: &common-variables
   QUEUE_NAME: links
   RABBITMQ_URL: 'amqp://myuser:mqmq192618@rabbit:5672/%2F'

services:
  web:
    build: web/.
    ports:
      - "8080:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      <<: *common-variables
      DATABASE_URL: postgresql://user:dbdb192618@db/db
  loader:
      build: loader/.
      restart: on-failure
      depends_on:
        - rabbit
        - web
      links:
        - rabbit
        - web
      environment:
        <<: *common-variables
        WEB_BASE_URL: 'http://web:8000'
  db:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: dbdb192618
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - "dbdata://var/lib/postgresql/data"
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mqmq192618
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  dbdata: